M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.04.1} date So 22 Jan 2023 12:34:55 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-22T12:34:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X56.9Y-44.5
X56.9Y-74.4
X86.87Y-44.5
X86.9Y-74.4
T0
M30
